<?php
$escaper = $block->getEscaper ? $block->getEscaper() : \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);
$clientKey = $escaper->escapeHtml($clientKey);
?>
<!-- ConvertCart Event-->
<script type='text/javascript' data-cfasync="false">
    window.ccLayer = window.ccLayer || [];
    ccLayer.push(<?= $escaper->escapeJs($eventData) ?>);
</script>
<!-- ConvertCart Event -->