<?php
$escaper = null;
if (is_callable([$block, 'getEscaper'])) {
    $escaper = $block->getEscaper();
} else {
    $escaper = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);
}
$jsEventData = json_encode($eventData);
?>
<!-- ConvertCart Event-->
<script type='text/javascript' data-cfasync="false">
    window.ccLayer = window.ccLayer || [];
    ccLayer.push(JSON.parse(<?= $jsEventData ?>));
</script>
<!-- ConvertCart Event -->